arb-dir: lib/l10n/arb
output-dir: lib/l10n/output
template-arb-file: app_cs.arb
output-localization-file: l10n.dart
untranslated-messages-file: lib/l10n/untranslated_messages.json
output-class: L10n
format: true
use-escaping: true
nullable-getter: false
