name: '[Flutter] Deploy Everything'
on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'android/**'
      - 'assets/**'
      - 'ios/**'
      - 'lib/**'
      - 'test/**'
      - 'pubspec.yaml'
      - 'analysis_options.yaml'
  workflow_dispatch:
    inputs:
      android:
        description: 'Deploy Android?'
        required: true
        type: boolean
        default: true
      ios:
        description: 'Deploy iOS?'
        required: true
        type: boolean
        default: true
      skip:
        description: 'Increment build number instead?'
        required: true
        type: boolean
        default: false

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: 'deploy'
  cancel-in-progress: false

jobs:
  version:
    permissions:
      contents: write
    name: Create version number
    environment:
      name: app-store
    if: ${{ github.event.pull_request.merged == true || (github.event_name == 'workflow_dispatch' && github.event.inputs.skip != 'true') }}
    # Works only on ubuntu
    runs-on: blacksmith-4vcpu-ubuntu-2204
    outputs:
      build_number: ${{ steps.version.outputs.build_number }}
      full_version: ${{ steps.version.outputs.full_version }}
      version: ${{ steps.version.outputs.version }}
      app_id: ${{ steps.extract_app_id.outputs.app_id }}
      firebase_id: ${{ steps.firebase_id.outputs.firebase_id }}
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from branch name or merge commit
        run: |
          version=""
          if [[ "${GITHUB_REF#refs/heads/}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Branch name matches the pattern *.*.* - stopping"
            echo "${GITHUB_REF#refs/heads/}+${{ github.run_number }}" > version.txt
            exit 0
          fi
          echo "Branch name doesn't match the pattern *.*.* - continuing"
          # Initialize a variable to keep track of the number of merge commits checked
          count=0
          # Loop until a matching merge commit is found
          while [[ ! -n $version ]]; do
            # Get the latest merge commit message starting from the most recent one and moving backwards
            commit_message=$(git log --merges -1 --skip=$count --pretty=%B)
            
            # Check if the commit message contains a version number in the format *.*.*
            if [[ $commit_message =~ [0-9]+\.[0-9]+\.[0-9]+ ]]; then
              # Extract the version number
              echo "Found a version number in the commit message"
              version=$(echo "$commit_message" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | head -n 1)
              break
            fi

            # Increment the counter to check the next merge commit in the next iteration
            count=$((count + 1))

            # Optional: Add a condition to exit the loop if too many commits have been checked
            if [ $count -gt 100 ]; then
              echo "Latest merge isn't from a branch matching *.*.* - Either repo rules are set wrong or somebody bypassed protections or it was ran from a different branch than main or version branch"
              exit 1
            fi
          done
          echo "$version+${{ github.run_number }}"
          echo "$version+${{ github.run_number }}" > version.txt

      - name: Update version in YAML
        run: |
          sed -i "s/^version: .*/version: $(tr -d '\n' < version.txt)/" pubspec.yaml

      - name: Upload version
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: version.txt

      - name: Set version as variables
        id: version
        run: |
          # Extract version, build_number, and full_version
          version=$(sed 's/\+.*//' version.txt | tr -d '\n')
          build_number=$(sed 's/.*+//' version.txt | tr -d '\n')
          full_version=$(cat version.txt | tr -d '\n')

          # Log to the console
          echo "version: $version"
          echo "build_number: $build_number"
          echo "full_version: $full_version"

          # Output to $GITHUB_OUTPUT
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "build_number=$build_number" >> "$GITHUB_OUTPUT"
          echo "full_version=$full_version" >> "$GITHUB_OUTPUT"

      - name: Upload pubspec.yaml
        uses: actions/upload-artifact@v4
        with:
          name: pubspec
          path: pubspec.yaml

      - name: Get applicationId
        id: extract_app_id
        run: |
          application_id=$(grep -oP 'applicationId\s*=\s*"\K[^"]+' android/app/build.gradle.kts)
          echo "app_id=$application_id"
          echo "app_id=$application_id" >> "$GITHUB_OUTPUT"

      - name: Get Firebase app id
        id: firebase_id
        run: |
          firebase_id=$(grep -A 2 'static const FirebaseOptions android' lib/firebase_options.dart | grep 'appId' | awk -F"'" '{print $2}')
          echo "firebase_id=$firebase_id"
          echo "firebase_id=$firebase_id" >> "$GITHUB_OUTPUT"

      - name: Create version tag
        id: tag
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add pubspec.yaml
          git commit -m "Update app version to $(cat version.txt)" || true
          VERSION_PREFIX="$(cat version.txt)"
          # Get the highest existing patch tag, if any

          NEW_TAG="${VERSION_PREFIX}"

          git tag $NEW_TAG # Create the tag
          git push -u origin $NEW_TAG # Push the tag

          echo "tag=$NEW_TAG" >> "$GITHUB_OUTPUT"

      - name: Run iOS Deployment
        if: ${{ github.event.pull_request.merged == true || github.event.inputs.ios == 'true' }}
        run: |
          LABEL=""

          PAYLOAD=$(cat <<EOF
          {
            "appId": "${{ vars.CODEMAGIC_APP_ID }}",
            "workflowId": "deploy_ios",
            "tag": "${{ steps.tag.outputs.tag }}",
            $LABEL
            "environment": {
              "variables": {
                "FLUTTER_VERSION": "${{ vars.FLUTTER_VERSION }}"
              },
              "softwareVersions": {
                "flutter": "${{ vars.FLUTTER_VERSION }}"
              }
            }
          }
          EOF
          )

          curl -H "Content-Type: application/json" \
               -H "x-auth-token: ${{ secrets.CODEMAGIC_TOKEN }}" \
               --data "$PAYLOAD" \
               -X POST https://api.codemagic.io/builds

  deploy_android:
    name: '[Android] Deploy to Google Play Store'
    environment:
      name: google-play
      url: https://play.google.com/store/apps/details?id=${{ needs.version.outputs.app_id }}
    needs: version
    if: ${{ github.event.pull_request.merged == true || github.event.inputs.android == 'true' }}
    # Works on ubuntu and macOS.
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get pubspec
        uses: actions/download-artifact@v4
        with:
          name: pubspec

      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties

      - name: Setup Java
        uses: useblacksmith/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17.x'
          cache: 'gradle'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          cache: true

      - name: Build AAB
        run: flutter build appbundle --release --obfuscate --split-debug-info=symbolsAndroid

      - name: Symbols extraction
        run: |
          PATH_TO_NATIVE_SYMBOLS="build/app/intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib"
          CURRENT_EXECUTION_PATH=$(pwd)
          cd $PATH_TO_NATIVE_SYMBOLS
          zip -r symbols.zip .
          cd $CURRENT_EXECUTION_PATH
          mv $PATH_TO_NATIVE_SYMBOLS/symbols.zip build/symbols.zip
      - uses: vacxe/google-play-cli-kt@0.4.8
        env:
          JAVA_HOME: ''
        with:
          service-account-json: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
          package-name: ${{needs.version.outputs.app_id}}
          custom-script: 'sh scripts/ci/deploy_google_play.sh build/app/outputs/bundle/release/app-release.aab ${{ needs.version.outputs.build_number }} internal completed build/app/outputs/mapping/release/mapping.txt build/symbols.zip'

      - name: Release Artifact Upload
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Debug symbols Artifact Upload
        uses: actions/upload-artifact@v4
        with:
          name: symbolsAndroid
          path: symbolsAndroid

  symbols_android:
    name: '[Android] Upload Crashlytics Symbols'
    # Doesn't work on ubuntu, Windows works sometimes but it's super slow. macOS is the best option even with the 10x
    runs-on: macos-latest
    needs:
      - version
      - deploy_android
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Android debug symbols from artifacts
        uses: actions/download-artifact@v4
        with:
          name: symbolsAndroid
          path: symbolsAndroid

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Upload Crashlytics Symbols
        run: |
          firebase crashlytics:symbols:upload --non-interactive --app=${{needs.version.outputs.firebase_id}} symbolsAndroid
