name: Update Pubspec Version

on:
  create:
    branches:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  update-version:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set pubspec version
        id: setVersion
        uses: mikefarah/yq@master
        with:
          cmd: yq -i ".version = \"${GITHUB_REF#refs/heads/}\"" pubspec.yaml

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit version change
        run: |
          git add pubspec.yaml
          git commit -m "Update pubspec version to ${GITHUB_REF#refs/heads/}" -S || echo "No changes to commit"

      - name: Push changes
        run: git push
